apiVersion: apps/v1
kind: Deployment
metadata:
  name: deepfence-logstash
  labels:
    {{- include "deepfence-console.labels" . | nindent 4 }}
    app: deepfence-console
    name: deepfence-logstash
  namespace: {{ .Release.Namespace }}
spec:
  {{- if not .Values.logstash.autoscaling.enabled }}
  replicas: {{ .Values.logstash.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      name: deepfence-logstash
      {{- include "deepfence-console.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: deepfence-console
        name: deepfence-logstash
        {{- include "deepfence-console.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.image.pullSecretName }}
      containers:
        - name: deepfence-logstash
          image: "{{ .Values.registry.imagePrefix }}{{ .Values.logstash.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.logstash.image.pullPolicy }}
          env:
            - name: ELASTICSEARCH_HOST
              valueFrom:
                configMapKeyRef:
                  name: "main-cm-{{ include "deepfence-console.fullname" . }}"
                  key: elasticsearch_host
            - name: ELASTICSEARCH_PORT
              valueFrom:
                configMapKeyRef:
                  name: "main-cm-{{ include "deepfence-console.fullname" . }}"
                  key: elasticsearch_port
            - name: ELASTICSEARCH_SCHEME
              valueFrom:
                configMapKeyRef:
                  name: "main-cm-{{ include "deepfence-console.fullname" . }}"
                  key: es_scheme
            {{- if .Values.db.elasticsearch.user }}
            - name: ELASTICSEARCH_USER
              valueFrom:
                secretKeyRef:
                  name: "es-secret-{{ include "deepfence-console.fullname" . }}"
                  key: es_user
            {{- end }}
            {{- if .Values.db.elasticsearch.password }}
            - name: ELASTICSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "es-secret-{{ include "deepfence-console.fullname" . }}"
                  key: es_password
            {{- end }}
            {{- if .Values.saas_deployment }}
            - name: CUSTOMER_UNIQUE_ID
              valueFrom:
                secretKeyRef:
                  name: "es-secret-{{ include "deepfence-console.fullname" . }}"
                  key: es_customer_unique_id
            {{- end }}
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: "main-cm-{{ include "deepfence-console.fullname" . }}"
                  key: redis_host
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: "main-cm-{{ include "deepfence-console.fullname" . }}"
                  key: redis_port
          ports:
            - containerPort: 8005
          resources:
            requests:
              memory: 850Mi
              cpu: {{ .Values.defaultResourceLimits.requests.cpu }}
            limits:
              memory: 2Gi
{{- if .Values.setDefaultResourceLimits }}
              cpu: {{ .Values.defaultResourceLimits.limits.cpu }}
{{- end }}
      {{- with .Values.logstash.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.logstash.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
