---
apiVersion: v1
kind: Service
metadata:
  name: deepfence-logstash
  labels:
    {{- include "deepfence-console.labels" . | nindent 4 }}
    app: deepfence-console
    name: deepfence-logstash
  namespace: {{ .Release.Namespace }}
spec:
  type:  {{ .Values.logstash.service.type }}
  selector:
    name: deepfence-logstash
  ports:
    - name: deepfence-logstash
      port: 8005
      protocol: TCP
      targetPort: 8005
